# to get started with dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # see documentation for possible values
    directory: "/" # location of package manifests
    schedule:
      interval: "weekly"
